const categories = ["Tresses & coiffure", "Soins des cheveux naturels", "Soins du cuir chevelu", "Onglerie", "Cils & sourcils", "Maquillage", "Épilation", "Soins du visage", "Massage & spa"];
const locations = ["Haie Vive", "Cadjèhoun", "Fidjrossè", "Akpakpa", "Zongo", "Ganhi", "Agla"];
const providers = [
  { id: "naya", name: "Naya Beauty Studio", category: "Soins du cuir chevelu", searchCategories: ["Soins du cuir chevelu", "Soins des cheveux naturels"], location: "Haie Vive, Cotonou", rating: "4,8", reviews: 28, services: [{ name: "Soin du cuir chevelu", price: 15000, duration: "1h" }, { name: "Diagnostic cheveux naturels", price: 8000, duration: "30 min" }], availability: "Aujourd'hui à 14:00", estimatedWait: "10–15 min", image: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=700&q=85", description: "Un espace calme dédié aux cheveux naturels et aux rituels de soin. Chaque séance commence par un diagnostic personnalisé." },
  { id: "kora", name: "Kora Beauty House", category: "Tresses & coiffure", searchCategories: ["Tresses & coiffure", "Soins des cheveux naturels"], location: "Fidjrossè, Cotonou", rating: "4,6", reviews: 19, services: [{ name: "Tresses protectrices", price: 25000, duration: "3h" }, { name: "Nattes simples", price: 12000, duration: "1h30" }], availability: "Demain à 10:00", estimatedWait: "20–30 min", image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=700&q=85", description: "Une adresse chaleureuse pour les cheveux afro et les styles protecteurs, dans une atmosphère attentive." },
  { id: "mina", name: "Mina Tresses Atelier", category: "Tresses & coiffure", searchCategories: ["Tresses & coiffure"], location: "Zongo, Cotonou", rating: "4,7", reviews: 23, services: [{ name: "Cornrows créatives", price: 18000, duration: "2h30" }, { name: "Tresses sans noeuds", price: 30000, duration: "3h30" }], availability: "Samedi à 11:00", estimatedWait: "15–25 min", image: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=700&q=85", description: "Un atelier spécialisé dans les tresses protectrices et les finitions nettes pour cheveux afro." },
  { id: "eclat", name: "Éclat Studio", category: "Soins du visage", searchCategories: ["Soins du visage", "Maquillage"], location: "Cadjèhoun, Cotonou", rating: "4,9", reviews: 41, services: [{ name: "Soin visage éclat", price: 18000, duration: "1h15" }, { name: "Maquillage naturel", price: 16000, duration: "1h" }], availability: "Aujourd'hui à 16:00", estimatedWait: "5–10 min", image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=700&q=85", description: "Un studio contemporain pour les soins du visage et les mises en beauté naturelles, sur rendez-vous." },
  { id: "luma", name: "Luma Nails & Beauty", category: "Onglerie", searchCategories: ["Onglerie", "Cils & sourcils"], location: "Akpakpa, Cotonou", rating: "4,7", reviews: 34, services: [{ name: "Manucure gel", price: 12000, duration: "1h" }, { name: "Beauté des pieds", price: 10000, duration: "45 min" }], availability: "Samedi à 09:30", estimatedWait: "15–20 min", image: "https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=700&q=85", description: "Un nail bar urbain pour des manucures soignées et des rendez-vous ponctuels, dans un cadre lumineux." },
  { id: "ayo", name: "Ayo Spa & Care", category: "Massage & spa", searchCategories: ["Massage & spa", "Soins du visage"], location: "Ganhi, Cotonou", rating: "4,5", reviews: 16, services: [{ name: "Massage relaxant", price: 20000, duration: "1h30" }, { name: "Soin visage détente", price: 15000, duration: "1h" }], availability: "Samedi à 13:00", estimatedWait: "30–40 min", image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=700&q=85", description: "Un spa contemporain consacré aux massages et aux rituels de détente, dans une atmosphère apaisante." }
];
const app = document.querySelector("#app");
const state = { selectedProvider: providers[0], selectedSlot: "14:00", selectedDate: "Samedi 5 septembre", search: "Soins du cuir chevelu", firstName: "", phone: "", ratings: { quality: 5, welcome: 5, punctuality: 4, wait: 4 } };

function layout(content) { return `<div class="page-enter">${content}</div>`; }
function rating(provider) { return `<span class="rating">★ ${provider.rating}/5</span><span class="verified">● ${provider.reviews} avis vérifiés</span>`; }
function findProvider(id) { return providers.find(provider => provider.id === id) || providers[0]; }
function categoryButtons() { return categories.map((name, index) => `<button class="category" data-action="search-category" data-category="${name}"><span class="category-icon">${["✦", "⌁", "◒", "○", "✧", "◇", "◌", "❋", "♡"][index]}</span><small>${name}</small></button>`).join(""); }
function serviceOptions() { return `<option value="" disabled ${state.search ? "" : "selected"}>Choisir une prestation</option>${categories.map(category => `<option value="${category}" ${state.search === category ? "selected" : ""}>${category}</option>`).join("")}`; }

function homeView() {
  return layout(`<section class="hero"><div class="hero-inner"><div class="hero-copy"><span class="eyebrow">Beauté locale, choisie avec soin</span><h1>Trouvez votre prochain rendez-vous beauté en toute confiance.</h1><p>Découvrez des prestataires beauté à Cotonou, comparez les expériences clientes et réservez selon vos disponibilités.</p><div class="search-panel"><div class="search-field"><span>⌕</span><div><label for="service">Je cherche</label><select id="service" aria-label="Que recherchez-vous ?">${serviceOptions()}</select></div></div><div class="search-field"><span>⌖</span><div><label for="place">Où ?</label><input id="place" value="Cotonou" list="locations" aria-label="Où ?"></div><datalist id="locations">${locations.map(location => `<option value="${location}, Cotonou">`).join("")}</datalist></div><button class="btn" data-action="search">Rechercher <span>→</span></button></div></div><div class="hero-visual"><img src="https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=85" alt="Femme noire dans un espace beauté contemporain"><div class="visual-note"><strong>4,9 / 5</strong><span>28 expériences vérifiées</span></div></div></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">Explorer</span><h2>Un moment pour vous</h2></div><p>Des soins choisis pour votre quotidien à Cotonou.</p></div><div class="category-grid">${categoryButtons()}</div></section><section class="trust-band"><div class="trust-inner"><div class="trust-item"><b>✓</b><span><strong>CONFIANCE</strong><br>4,9 / 5<br>28 expériences vérifiées</span></div><div class="trust-item"><b>★</b><span><strong>DISPONIBILITÉ</strong><br>Créneaux visibles<br>en temps réel</span></div><div class="trust-item"><b>◷</b><span><strong>FIABILITÉ</strong><br>Expérience<br>évaluée</span></div></div></section>`);
}
function resultsView() {
  const filtered = providers.filter(provider => provider.searchCategories.includes(state.search));
  const visibleProviders = filtered.length ? filtered : providers;
  return layout(`<div class="container"><span class="eyebrow">Résultats à Cotonou</span><div class="results-toolbar"><div><h1>Trouvez une adresse qui vous correspond</h1><p>Comparez les expériences, les prestations et les disponibilités.</p></div><span>${visibleProviders.length} établissements</span></div><div class="results-grid">${visibleProviders.map(provider => { const service = provider.services[0]; return `<article class="provider-card"><img src="${provider.image}" alt="${provider.name}"><div><h3>${provider.name}</h3><p class="provider-category">${provider.category} · ${provider.location}</p><div class="provider-meta"><span class="rating">★ ${provider.rating}/5</span><span class="verified">● ${provider.reviews} expériences vérifiées</span></div><p class="provider-description">${provider.description}</p><div class="price">À partir de ${service.price.toLocaleString("fr-FR")} FCFA · ${service.duration}</div><div class="availability">● Attente estimée : ${provider.estimatedWait}</div><div class="availability">Prochaine disponibilité : ${provider.availability}</div></div><button class="btn secondary" data-action="profile" data-id="${provider.id}">Voir le profil <span>→</span></button></article>`; }).join("")}</div></div>`);
}
function profileView() {
  const provider = state.selectedProvider;
  const mainService = provider.services[0];
  const criteria = [["Qualité du service", "4,9/5", "98"], ["Accueil", "4,8/5", "96"], ["Ponctualité", "4,5/5", "90"], ["Respect du temps annoncé", "4,3/5", "86"]];
  const reviews = [["4,9/5", "Aïcha", mainService.name, "Le diagnostic était très précis et la prestation vraiment apaisante."], ["4,8/5", "Sonia", mainService.name, "Un accueil doux, et surtout aucun temps d'attente à mon arrivée."], ["4,7/5", "Nadia", mainService.name, "Une prestation fidèle aux photos, avec des conseils très utiles."]];
  return layout(`<div class="container"><div class="profile-hero"><img src="${provider.image}" alt="${provider.name}"><div><span class="eyebrow">Fiche prestataire</span><h1>${provider.name}</h1><p class="location">⌖ ${provider.location}</p><div class="provider-meta">${rating(provider)} <span class="verified">Établissement vérifié</span></div><p class="profile-intro">${provider.description}</p><strong>Prestations</strong><div class="tag-list">${provider.services.map(service => `<span class="tag">${service.name} · ${service.price.toLocaleString("fr-FR")} FCFA · ${service.duration}</span>`).join("")}</div></div></div><div class="profile-columns"><section><h2 class="subheading">Ce que disent les clientes</h2>${criteria.map(([label, value, width]) => `<div class="metric"><div class="metric-row"><span>${label}</span><span>${value}</span></div><div class="meter"><i style="width:${width}%"></i></div></div>`).join("")}<div class="availability-preview"><strong>Attente estimée</strong><span>${provider.estimatedWait}</span></div></section><section><h2 class="subheading">Expériences récentes</h2><p class="demo-note">Données de démonstration</p>${reviews.map(([score, name, service, text]) => `<div class="review"><div class="review-head"><span class="rating">${score}</span><span>${name}</span></div><p><strong>${service}</strong><br>${text}</p><span class="demo-note">Expérience vérifiée ✓</span></div>`).join("")}<div class="availability-preview"><strong>Prochaines disponibilités</strong><span>${provider.availability}</span></div><button class="btn secondary" data-action="reviews">Voir les avis <span>→</span></button> <button class="btn" data-action="booking">Choisir un créneau <span>→</span></button></section></div></div>`);
}
function slotsFor(date, times) { const dateValue = date === "Aujourd'hui" ? "Samedi 5 septembre" : "Dimanche 6 septembre"; return `<div class="date-group"><div class="date-label">${date}<span>${dateValue}</span></div><div class="slots">${times.map(time => `<button class="slot ${state.selectedSlot === time && state.selectedDate === dateValue ? "selected" : ""} ${time === "18:00" ? "full" : ""}" data-action="slot" data-slot="${time}" data-date="${dateValue}" ${time === "18:00" ? "disabled" : ""}><strong>${time}</strong><small>${time === "18:00" ? "Complet" : "Disponible"}</small></button>`).join("")}</div></div>`; }
function bookingView() { const provider = state.selectedProvider; const service = provider.services[0]; return layout(`<div class="container"><div class="booking-shell"><span class="eyebrow">Disponibilités · ${provider.name}</span><h1>Quand souhaitez-vous venir ?</h1><p class="booking-subtitle">${service.name} · ${service.price.toLocaleString("fr-FR")} FCFA · ${service.duration}</p>${slotsFor("Aujourd'hui", ["14:00", "16:00", "18:00"])}${slotsFor("Demain", ["10:00", "14:00", "16:00"])}<div class="selected-slot">Créneau choisi : <strong>${state.selectedDate}, ${state.selectedSlot}</strong></div><div class="booking-footer"><span>Les créneaux sont indicatifs et seront confirmés par l'établissement.</span><button class="btn" data-action="continue">Continuer <span>→</span></button></div></div></div>`); }
function reservationView() { const provider = state.selectedProvider; const service = provider.services[0]; return layout(`<div class="container"><div class="reservation-layout"><div><span class="eyebrow">Dernière étape</span><h1>Confirmez votre demande</h1><p class="booking-subtitle">Une simple demande, sans paiement en ligne.</p><div class="confirm-card"><div class="confirm-row"><span>Établissement</span><strong>${provider.name}</strong></div><div class="confirm-row"><span>Prestation</span><strong>${service.name}</strong></div><div class="confirm-row"><span>Date</span><strong>${state.selectedDate}</strong></div><div class="confirm-row"><span>Heure</span><strong>${state.selectedSlot}</strong></div><div class="confirm-row"><span>Prix</span><strong>${service.price.toLocaleString("fr-FR")} FCFA</strong></div></div></div><form class="reservation-form" data-action="reservation-form"><label for="first-name">Prénom</label><input id="first-name" name="firstName" value="${state.firstName}" placeholder="Votre prénom" required><label for="phone">Téléphone</label><input id="phone" name="phone" value="${state.phone}" placeholder="Votre numéro de téléphone" type="tel" required><button class="btn" type="submit">Confirmer ma demande <span>→</span></button></form></div></div>`); }
function confirmationView() { const provider = state.selectedProvider; const service = provider.services[0]; return layout(`<div class="container"><div class="confirmation"><div class="confirm-icon">✓</div><span class="eyebrow" style="justify-content:center">Demande envoyée</span><h1>Votre demande est envoyée</h1><p>Nous avons transmis votre demande à l'établissement.</p><div class="confirm-card"><div class="confirm-row"><span>Établissement</span><strong>${provider.name}</strong></div><div class="confirm-row"><span>Prestation</span><strong>${service.name}</strong></div><div class="confirm-row"><span>Date</span><strong>${state.selectedDate}</strong></div><div class="confirm-row"><span>Heure</span><strong>${state.selectedSlot}</strong></div><div class="confirm-row"><span>Prix</span><strong>${service.price.toLocaleString("fr-FR")} FCFA</strong></div></div><p>Vous recevrez une confirmation du prestataire.</p><button class="btn secondary" data-route="home">Retour à l'accueil</button></div></div>`); }
function reviewsView() { return layout(`<div class="container"><div class="review-form"><span class="eyebrow">Votre expérience</span><h1>Partagez votre expérience</h1><p>Votre avis aide la communauté à faire des choix éclairés.</p>${[["quality", "Qualité"], ["welcome", "Accueil"], ["punctuality", "Ponctualité"], ["wait", "Temps d'attente"]].map(([key, label]) => `<div class="rating-block"><label>${label}</label><div class="rating-buttons">${[1, 2, 3, 4, 5].map(value => `<button type="button" class="${value <= (state.ratings?.[key] || 5) ? "active" : ""}" data-action="rate" data-key="${key}" data-value="${value}" aria-label="${value} sur 5">★</button>`).join("")}</div></div>`).join("")}<div class="recommend"><strong>Recommanderiez-vous ce prestataire ?</strong><label class="toggle"><input type="checkbox" checked> Oui, je le recommande</label></div><button class="btn" data-action="publish">Publier mon avis <span>→</span></button></div></div>`); }

function render(route = "home") { const views = { home: homeView, results: resultsView, profile: profileView, booking: bookingView, reservation: reservationView, confirmation: confirmationView, reviews: reviewsView }; app.innerHTML = (views[route] || homeView)(); window.scrollTo({ top: 0, behavior: "smooth" }); }
document.addEventListener("submit", event => { if (!event.target.matches("[data-action='reservation-form']")) return; event.preventDefault(); const form = new FormData(event.target); state.firstName = form.get("firstName"); state.phone = form.get("phone"); render("confirmation"); });
document.addEventListener("click", event => { const target = event.target.closest("[data-route], [data-action]"); if (!target) return; const action = target.dataset.action; if (target.dataset.route) { event.preventDefault(); render(target.dataset.route); return; } if (action === "search" || action === "search-category") { if (action === "search") state.search = document.querySelector("#service")?.value || state.search; else state.search = target.dataset.category; render("results"); } if (action === "profile") { state.selectedProvider = findProvider(target.dataset.id); render("profile"); } if (action === "booking") render("booking"); if (action === "slot") { state.selectedSlot = target.dataset.slot; state.selectedDate = target.dataset.date; render("booking"); } if (action === "continue") render("reservation"); if (action === "rate") { state.ratings[target.dataset.key] = Number(target.dataset.value); render("reviews"); } if (action === "publish") { target.textContent = "Avis publié ✓"; target.disabled = true; } });
render();
